---
- hosts: all
  become: yes
  roles:
  - base
  - role: ruby
    vars:
      ruby_version: '3.1.4'
      ruby_make_default: true
  - role: nodejs
    vars:
      node_version: '20.x'
  - apache
  - role: shibboleth
    vars:
      shibboleth_sp_description: "UMass Parking Hub"
      shibboleth_idp_host: webauth.umass.edu
      shibboleth_idp_entity_id: 'https://webauth.umass.edu/idp/shibboleth'
      shibboleth_idp_metadata_url: 'https://webauth.umass.edu/idp/shibboleth'
  - mariadb
  - passenger
  - role: rails-app
    vars:
      rails_app_name: umaps-rails
      rails_production_key_kp_path: rails/umaps-rails/production.key
      rails_database:
        database: umaps-rails-production
        host: umwebdb.umass.edu
        port: 3308
        username: umaps-rail-production
        password_kp_path: databases/umaps-rails
      rails_needs_sidekiq: true
