---
- name: Logrotate configuration
  template:
    src: logrotate.conf.j2
    dest: "/etc/logrotate.d/{{ rails_app_name }}"
    owner: root
    group: root
    mode: 0644
    validate: logrotate -d %s
