---
- name: App user
  user:
    name: "{{ rails_app_name }}"
    state: present
    system: yes

- name: Deploy group
  group:
    name: deploy
    state: present

- name: Allow deploy group to sudo
  copy:
    src: deploy_sudo
    dest: /etc/sudoers.d/deploy
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s

- name: Vagrant user in deploy group
  user:
    name: vagrant
    groups: deploy
    append: yes
  when: running_in_vagrant is defined and running_in_vagrant == true

- name: Deployment directory
  file:
    path: /srv/{{ rails_app_name }}
    state: directory
    owner: "{{ rails_app_name }}"
    group: deploy
    mode: 0o6775

- name: Config directory
  file:
    path: /srv/{{ rails_app_name }}/shared/config
    state: directory
    owner: "{{ rails_app_name }}"
    group: deploy
    mode: 0o6775

- import_tasks: production_key.yml
- import_tasks: database_config.yml
- import_tasks: site_config.yml
- import_tasks: logrotate.yml

- include_tasks: sidekiq.yml
  when: rails_needs_sidekiq == true
