---
- name: Require variables
  assert:
    that:
      - "item is defined"
      - "item != ''"
    msg: "{{ item }} is required"
  with_items:
    - rails_app_name
    - rails_production_key_kp_path

- name: App user
  user:
    name: "{{ rails_app_name }}"
    state: present
    system: yes

- name: Deploy group
  group:
    name: deploy
    state: present

- name: Vagrant user in deploy group
  user:
    name: vagrant
    groups: deploy
    append: yes
  when: running_in_vagrant == true

- name: Deployment directory
  file:
    path: /srv/{{ rails_app_name }}
    state: directory
    owner: "{{ rails_app_name }}"
    group: deploy
    mode: 0o6775
- name: Config directory
  file:
    path: /srv/{{ rails_app_name }}/shared/config/credentials
    state: directory
    owner: "{{ rails_app_name }}"
    group: deploy
    mode: 0o6775

- name: Read production key
  become: false
  local_action:
    module: hasnimehdi91.keepass.secret_reader
    db_path: "{{ password_database_file }}"
    db_password: "{{ password_database_password }}"
    secret_path: "{{ rails_production_key_kp_path }}"
  register: production_key_secret

- name: Production key
  copy:
    dest: /srv/{{ rails_app_name }}/shared/config/credentials/production.key
    content: "{{ production_key_secret.secret['production.key'].password }}"
    owner: "{{ rails_app_name }}"
    group: deploy
    mode: 0o660
