---
- name: Install redis
  yum:
    name: redis
    state: present
- name: Redis service
  systemd:
    name: redis.service
    enabled: true
    state: started

- name: Sidekiq systemd unit
  template:
    src: sidekiq.service.j2
    dest: /etc/systemd/system/sidekiq-{{ rails_app_name }}.service
    owner: root
    group: root
    mode: 0o644

- name: Sidekiq service
  systemd:
    name: sidekiq-{{ rails_app_name }}
    enabled: true
    daemon_reload: true
