---
argument_specs:
  main:
    options:
      rails_app_name:
        required: true
        type: str
      rails_app_domain:
        required: true
        type: str
      rails_app_domain_hsts_preload:
        required: false
        type: bool
      rails_app_additional_domains:
        required: false
        type: list
        elements: str
      rails_production_key_kp_path:
        description: >
          The path to the production.key value within the password database
        required: true
        type: str
      rails_database:
        required: true
        type: dict
        options:
          adapter:
            required: true
            type: str
          database:
            required: true
            type: str
          host:
            required: true
            type: str
          port:
            required: true
            type: int
          username:
            required: true
            type: str
          password:
            desciption: >
              The password to the database. If ommmitted, the password will
              be retrieved from the password database.
            required: false
            type: str
          password_kp_path:
            description: >
              The path to the password within the password database. Can be
              omitted if the password is provided directly.
            required: false
            type: str
          other_databases:
            description: >
              Single string containing non-primary database YAML
            required: false
            type: str
