#!/bin/sh

set -e

cd "$(dirname "$0")/.."

if [ ! command -v direnv >/dev/null 2>&1 ]; then
  export PIPENV_VENV_IN_PROJECT=1
  if [ -f .venv/bin/activate ]; then
    source .venv/bin/activate
  else
    pipenv install --dev
  fi
fi

cp -n .envrc.example .envrc

.venv/bin/ansible-galaxy install -r requirements.yml
