#!/bin/sh

set -e

cd "$(dirname "$0")/.."

if ! command -v direnv &>/dev/null; then
  export PIPENV_VENV_IN_PROJECT=1
  if [ -f .venv/bin/activate ]; then
    echo "Run 'source .venv/bin/activate' to activate the virtualenv"
  else
    pipenv install --dev
  fi
fi

cp -n .envrc.example .envrc || true

.venv/bin/ansible-galaxy install -r requirements.yml
